In [1]:
import pandas  as pd
import numpy as np

In [6]:
#Read the training data and testing data
training_data = pd.read_excel('Titanic_Survival_train.xls', index_col=0, header=0)
testing_data = pd.read_excel('Titanic_Survival_test.xls', index_col=0, header=0)

print(training_data.shape)
print(testing_data.shape)

(891, 11)
(21, 11)


In [15]:
training_data.tail(22)

Name  Pclass     Sex  \
PassengerId                                                                     
870                           Johnson, Master. Harold Theodor       3    male   
871                                         Balkic, Mr. Cerin       3    male   
872          Beckwith, Mrs. Richard Leonard (Sallie Monypeny)       1  female   
873                                  Carlsson, Mr. Frans Olof       1    male   
874                               Vander Cruyssen, Mr. Victor       3    male   
875                     Abelson, Mrs. Samuel (Hannah Wizosky)       2  female   
876                          Najib, Miss. Adele Kiamie "Jane"       3  female   
877                             Gustafsson, Mr. Alfred Ossian       3    male   
878                                      Petroff, Mr. Nedelio       3    male   
879                                        Laleff, Mr. Kristo       3    male   
880             Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)       1  female   
881              Shelley, Mrs. William (Imanita Parrish Hall)       2  female   
882                                        Markun, Mr. Johann       3    male   
883                              Dahlberg, Miss. Gerda Ulrika       3  female   
884                             Banfield, Mr. Frederick James       2    male   
885                                    Sutehall, Mr. Henry Jr       3    male   
886                      Rice, Mrs. William (Margaret Norton)       3  female   
887                                     Montvila, Rev. Juozas       2    male   
888                              Graham, Miss. Margaret Edith       1  female   
889                  Johnston, Miss. Catherine Helen "Carrie"       3  female   
890                                     Behr, Mr. Karl Howell       1    male   
891                                       Dooley, Mr. Patrick       3    male   

                   Age  Survived  sex1  
PassengerId                             
870           4.000000         1     0  
871          26.000000         0     0  
872          47.000000         1     1  
873          33.000000         0     0  
874          47.000000         0     0  
875          28.000000         1     1  
876          15.000000         1     1  
877          20.000000         0     0  
878          19.000000         0     0  
879          29.699118         0     0  
880          56.000000         1     1  
881          25.000000         1     1  
882          33.000000         0     0  
883          22.000000         0     1  
884          28.000000         0     0  
885          25.000000         0     0  
886          39.000000         0     1  
887          27.000000         0     0  
888          19.000000         1     1  
889          29.699118         0     1  
890          26.000000         1     0  
891          32.000000         0     0

In [8]:
testing_data.head(21)

Survived  Pclass  \
PassengerId                     
871                 0       3   
872                 1       1   
873                 0       1   
874                 0       3   
875                 1       2   
876                 1       3   
877                 0       3   
878                 0       3   
879                 0       3   
880                 1       1   
881                 1       2   
882                 0       3   
883                 0       3   
884                 0       2   
885                 0       3   
886                 0       3   
887                 0       2   
888                 1       1   
889                 0       3   
890                 1       1   
891                 0       3   

                                                         Name     Sex   Age  \
PassengerId                                                                   
871                                         Balkic, Mr. Cerin    male  26.0   
872          Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0   
873                                  Carlsson, Mr. Frans Olof    male  33.0   
874                               Vander Cruyssen, Mr. Victor    male  47.0   
875                     Abelson, Mrs. Samuel (Hannah Wizosky)  female  28.0   
876                          Najib, Miss. Adele Kiamie "Jane"  female  15.0   
877                             Gustafsson, Mr. Alfred Ossian    male  20.0   
878                                      Petroff, Mr. Nedelio    male  19.0   
879                                        Laleff, Mr. Kristo    male   NaN   
880             Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0   
881              Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0   
882                                        Markun, Mr. Johann    male  33.0   
883                              Dahlberg, Miss. Gerda Ulrika  female  22.0   
884                             Banfield, Mr. Frederick James    male  28.0   
885                                    Sutehall, Mr. Henry Jr    male  25.0   
886                      Rice, Mrs. William (Margaret Norton)  female  39.0   
887                                     Montvila, Rev. Juozas    male  27.0   
888                              Graham, Miss. Margaret Edith  female  19.0   
889                  Johnston, Miss. Catherine Helen "Carrie"  female   NaN   
890                                     Behr, Mr. Karl Howell    male  26.0   
891                                       Dooley, Mr. Patrick    male  32.0   

             SibSp  Parch            Ticket     Fare        Cabin Embarked  
PassengerId                                                                 
871              0      0            349248   7.8958          NaN        S  
872              1      1             11751  52.5542          D35        S  
873              0      0               695   5.0000  B51 B53 B55        S  
874              0      0            345765   9.0000          NaN        S  
875              1      0         P/PP 3381  24.0000          NaN        C  
876              0      0              2667   7.2250          NaN        C  
877              0      0              7534   9.8458          NaN        S  
878              0      0            349212   7.8958          NaN        S  
879              0      0            349217   7.8958          NaN        S  
880              0      1             11767  83.1583          C50        C  
881              0      1            230433  26.0000          NaN        S  
882              0      0            349257   7.8958          NaN        S  
883              0      0              7552  10.5167          NaN        S  
884              0      0  C.A./SOTON 34068  10.5000          NaN        S  
885              0      0   SOTON/OQ 392076   7.0500          NaN        S  
886              0      5            382652  29.1250          NaN        Q  
887              0      0            211536  13.0

In [ ]:
training_data.isnull().sum()

In [9]:
#feature selection 
training_data = training_data[['Name','Pclass','Sex','Age','Survived']]
testing_data = testing_data[['Name','Pclass','Sex','Age','Survived']]


In [10]:
#finding the missing values
print(training_data.isnull().sum())
print()
print(testing_data.isnull().sum())

Name          0
Pclass        0
Sex           0
Age         177
Survived      0
dtype: int64

Name        0
Pclass      0
Sex         0
Age         2
Survived    0
dtype: int64


In [11]:
#imputing numerical missing data with mean value

training_data["Age"].fillna(training_data["Age"].mean(),inplace=True)
print(training_data.isnull().sum())

#imputing numerical missing data with mean value

testing_data["Age"].fillna(testing_data["Age"].mean(),inplace=True)
print(testing_data.isnull().sum())

Name        0
Pclass      0
Sex         0
Age         0
Survived    0
dtype: int64
Name        0
Pclass      0
Sex         0
Age         0
Survived    0
dtype: int64


In [14]:
training_data["sex1"]=training_data["Sex"].map({"male":0,"female":1})

In [16]:
#transforming categorical data to numerical

from sklearn import preprocessing

colname=['Sex']

le=preprocessing.LabelEncoder()

for x in colname:
    training_data[x]=le.fit_transform(training_data[x])
    testing_data[x]=le.fit_transform(testing_data[x])
    
# training_data['Sex']=training_data['Sex'].map({"female":0, "male":1})
# testing_data['Sex']=testing_data['Sex'].map({"female":0, "male":1})

In [20]:
training_data.head()

Name  Pclass  Sex  \
PassengerId                                                                   
1                                      Braund, Mr. Owen Harris       3    1   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...       1    0   
3                                       Heikkinen, Miss. Laina       3    0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)       1    0   
5                                     Allen, Mr. William Henry       3    1   

              Age  Survived  
PassengerId                  
1            22.0         0  
2            38.0         1  
3            26.0         1  
4            35.0         1  
5            35.0         0

In [19]:
training_data.drop("sex1", inplace=True, axis=1)

In [ ]:
testing_data.head()

In [21]:
X_train=training_data.values[:870,  1:-1] # variables from pclass to age [ observation ,  columns]
Y_train=training_data.values[:870,   -1] # passangersIds from 1 to 870 

# include test data in training 
# X_train=training_data.values[:,  1:-1]
# Y_train=training_data.values[:,   -1] 


Y_train=Y_train.astype(int)

 


X_test=testing_data.values[:, 1:-1]
Y_test=testing_data.values[:, -1]
Y_test=Y_test.astype(int)

In [22]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

# mean = 0 and std = 1

scaler = StandardScaler()

scaler.fit(X_train)

X_train_scale = scaler.transform(X_train)
X_test_scale = scaler.transform(X_test)


# while working on separate train and test data, fit the scaler oject only uplon the train data
# and use the same scaler object to transform both the train as well as the test data.

In [24]:
#predicting using the KNeighbors_Classifier
from sklearn.neighbors import KNeighborsClassifier

In [29]:
model_KNN = KNeighborsClassifier(n_neighbors=15)


#fit the model on the data and predict the values
model_KNN.fit(X_train,Y_train)

Y_pred=model_KNN.predict(X_test)

In [30]:
Y_pred

array([0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0])

In [27]:
Y_test

array([0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0])

In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

conf_matrix=confusion_matrix(Y_test,Y_pred)
print(conf_matrix)
print()


print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc_score=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc_score)

[[12  2]
 [ 4  3]]

Classification report: 
              precision    recall  f1-score   support

           0       0.75      0.86      0.80        14
           1       0.60      0.43      0.50         7

    accuracy                           0.71        21
   macro avg       0.68      0.64      0.65        21
weighted avg       0.70      0.71      0.70        21

Accuracy of the model:  0.7142857142857143


In [31]:


acc_dict = dict()
for K in range(1, 31):
    
    # create object with k value
    model_KNN = KNeighborsClassifier(K,metric='euclidean')
    
    # model fit 
    model_KNN.fit(X_train, Y_train) 
    
    # model prediction
    Y_pred = model_KNN.predict(X_test)
    
    acc_score= round(accuracy_score(Y_test, Y_pred),2 )
    
    # print accuracy score
    print("Accuracy is: {} for K-Value: {}".format(acc_score,K))
    acc_dict[K] = acc_score

Accuracy is: 0.86 for K-Value: 1
Accuracy is: 0.81 for K-Value: 2
Accuracy is: 0.67 for K-Value: 3
Accuracy is: 0.67 for K-Value: 4
Accuracy is: 0.71 for K-Value: 5
Accuracy is: 0.67 for K-Value: 6
Accuracy is: 0.62 for K-Value: 7
Accuracy is: 0.71 for K-Value: 8
Accuracy is: 0.71 for K-Value: 9
Accuracy is: 0.71 for K-Value: 10
Accuracy is: 0.81 for K-Value: 11
Accuracy is: 0.67 for K-Value: 12
Accuracy is: 0.71 for K-Value: 13
Accuracy is: 0.67 for K-Value: 14
Accuracy is: 0.62 for K-Value: 15
Accuracy is: 0.67 for K-Value: 16
Accuracy is: 0.67 for K-Value: 17
Accuracy is: 0.71 for K-Value: 18
Accuracy is: 0.67 for K-Value: 19
Accuracy is: 0.57 for K-Value: 20
Accuracy is: 0.62 for K-Value: 21
Accuracy is: 0.62 for K-Value: 22
Accuracy is: 0.62 for K-Value: 23
Accuracy is: 0.62 for K-Value: 24
Accuracy is: 0.62 for K-Value: 25
Accuracy is: 0.62 for K-Value: 26
Accuracy is: 0.62 for K-Value: 27
Accuracy is: 0.62 for K-Value: 28
Accuracy is: 0.62 for K-Value: 29
Accuracy is: 0.62 for K

In [32]:
for k in acc_dict:
    if acc_dict[k] == max(acc_dict.values()):
        print(k,":", acc_dict[k])

1 : 0.86


In [33]:
model = KNeighborsClassifier(n_neighbors=11, metric="euclidean")

# model fit 
model.fit(X_train, Y_train) 

# model prediction
Y_pred = model.predict(X_test)


In [34]:
conf_matrix=confusion_matrix(Y_test,Y_pred)
print(conf_matrix)
print()


print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc_score=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc_score)

[[12  2]
 [ 2  5]]

Classification report: 
              precision    recall  f1-score   support

           0       0.86      0.86      0.86        14
           1       0.71      0.71      0.71         7

    accuracy                           0.81        21
   macro avg       0.79      0.79      0.79        21
weighted avg       0.81      0.81      0.81        21

Accuracy of the model:  0.8095238095238095


In [ ]:
# By using Logistic regression 

In [ ]:
#predicting using the KNeighbors_Classifier
from sklearn.linear_model import LogisticRegression

In [ ]:
model = LogisticRegression()

# model fit 
model.fit(X_train, Y_train) 

# model prediction
Y_pred = model.predict(X_test)


In [ ]:
conf_matrix=confusion_matrix(Y_test,Y_pred)
print(conf_matrix)



print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc_score=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc_score)

# KNN Regression 

In [ ]:
df = pd.read_csv("Advertising.csv", index_col=0)

In [ ]:
df.head()

In [ ]:
df.isnull().sum()

In [ ]:
df.columns

In [ ]:
X  = df[['TV', 'radio', 'newspaper']]
Y = df['sales']

In [ ]:
from sklearn.model_selection import train_test_split
#Split the data into test and train
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3,
                                                    random_state=10)  

In [ ]:
#predicting using the KNeighbors_Classifier
from sklearn.neighbors import KNeighborsRegressor
model_KNN = KNeighborsRegressor(n_neighbors=3, metric="euclidean")
#fit the model on the data and predict the values
model_KNN.fit(X_train,Y_train)
Y_pred=model_KNN.predict(X_test)

In [ ]:
from sklearn.metrics import r2_score, mean_squared_error
r2 = r2_score(Y_test,Y_pred)
mse = mean_squared_error(Y_test,Y_pred)
print(r2)
print(mse)

In [ ]:
0.83
1.59

In [ ]:


acc_dict = dict()
for K in range(1, 31):
    
    # create object with k value
    model_KNN = KNeighborsRegressor(n_neighbors=K, metric="euclidean")
    
    # model fit 
    model_KNN.fit(X_train, Y_train) 
    
    # model prediction
    Y_pred = model_KNN.predict(X_test)
    
    r2 = r2_score(Y_test,Y_pred)
    
    # print accuracy score
    print("Accuracy is: {} for K-Value: {}".format(r2,K))
    acc_dict[K] =r2